version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: SampleApp/BackEnd/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-net
    depends_on: []

  frontend:
    build:
      context: .
      dockerfile: SampleApp/FrontEnd/Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - WEATHER_URL=http://backend:8080
    networks:
      - app-net
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sampledb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
