openapi: 3.0.1
info:
  title: Cardano RWA Backend API
  version: 1.0.0
  description: |
    OpenAPI specification for the Cardano RWA .NET backend. This spec documents the available endpoints for the sample app, including weather forecasting.
servers:
  - url: http://localhost:8080
paths:
  /weatherforecast:
    get:
      summary: Get weather forecast
      description: Returns a list of weather forecast objects for the next 5 days.
      responses:
        '200':
          description: A list of weather forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
        temperatureF:
          type: integer
        summary:
          type: string
