global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'cardano-node'
    static_configs:
      - targets: ['cardano-node:3001']
    scrape_interval: 30s

  - job_name: 'ogmios'
    static_configs:
      - targets: ['ogmios:1337']
    scrape_interval: 30s

  - job_name: 'kupo'
    static_configs:
      - targets: ['kupo:1442']
    scrape_interval: 30s

  - job_name: 'submit-api'
    static_configs:
      - targets: ['submit-api:8090']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']