# Default values for cardano-rwa Helm chart
# This is a YAML-formatted file for Helm templates

replicaCount: 3

image:
  repository: cardano-rwa-backend
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9464"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.cardano-rwa.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cardano-rwa-tls
      hosts:
        - api.cardano-rwa.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

environment:
  ASPNETCORE_ENVIRONMENT: Production
  LOG_LEVEL: Information

secrets:
  # Provided via GitOps (ArgoCD) or Sealed Secrets
  database:
    host: postgres.cardano-rwa.svc.cluster.local
    port: 5432
    name: CardanoRWA
  redis:
    host: redis.cardano-rwa.svc.cluster.local
    port: 6379

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - cardano-rwa
          topologyKey: kubernetes.io/hostname

nodeSelector: {}

tolerations: []
