name: Docker Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./SampleApp/BackEnd
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:buildcache,mode=max
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./SampleApp/FrontEnd
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:buildcache,mode=max

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            # Release ${{ github.ref_name }}
            
            ## Docker Images
            - Backend: `${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:${{ github.ref_name }}`
            - Frontend: `${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:${{ github.ref_name }}`
            
            ## Installation
            ```bash
            docker pull ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-backend:${{ github.ref_name }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/cardano-rwa-frontend:${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
